
import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JToggleButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author wylla
 */
public class teste extends javax.swing.JFrame {
    private Object me;
    private Object jmens;

    /**
     * Creates new form teste
     */
    public teste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonmanu = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jteste = new javax.swing.JButton();
        jsim1 = new javax.swing.JToggleButton();
        jsim2 = new javax.swing.JToggleButton();
        jsim3 = new javax.swing.JToggleButton();
        jsim4 = new javax.swing.JToggleButton();
        jsim5 = new javax.swing.JToggleButton();
        jnao1 = new javax.swing.JToggleButton();
        jnao2 = new javax.swing.JToggleButton();
        jnao3 = new javax.swing.JToggleButton();
        jnao4 = new javax.swing.JToggleButton();
        jnao5 = new javax.swing.JToggleButton();
        jmen = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(760, 490));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Formulario para encaminhamento.");

        jButtonmanu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonmanu.setText("Menu");
        jButtonmanu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jButtonmanuMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonmanuMouseMoved(evt);
            }
        });
        jButtonmanu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmanuActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(153, 153, 153));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setText("Você esta com sintomas de Gripe?");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(153, 153, 153));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.setText("você Viajou para aréas afetadas?");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(153, 153, 153));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField3.setText("Você entrou em contato com algue que viajou?");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(153, 153, 153));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField4.setText("Você tem mais de 60 anos?");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(153, 153, 153));
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField5.setText("Você tem menos de 18?");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jteste.setBackground(new java.awt.Color(189, 154, 55));
        jteste.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jteste.setText("Testar");
        jteste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtesteActionPerformed(evt);
            }
        });

        jsim1.setBackground(new java.awt.Color(51, 255, 0));
        jsim1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jsim1.setText("SIM");
        jsim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsim1ActionPerformed(evt);
            }
        });

        jsim2.setBackground(new java.awt.Color(51, 255, 0));
        jsim2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jsim2.setText("SIM");
        jsim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsim2ActionPerformed(evt);
            }
        });

        jsim3.setBackground(new java.awt.Color(51, 255, 0));
        jsim3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jsim3.setText("SIM");
        jsim3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsim3ActionPerformed(evt);
            }
        });

        jsim4.setBackground(new java.awt.Color(51, 255, 0));
        jsim4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jsim4.setText("SIM");
        jsim4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsim4ActionPerformed(evt);
            }
        });

        jsim5.setBackground(new java.awt.Color(51, 255, 0));
        jsim5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jsim5.setText("SIM");
        jsim5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsim5ActionPerformed(evt);
            }
        });

        jnao1.setBackground(new java.awt.Color(255, 0, 0));
        jnao1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jnao1.setText("NAO");
        jnao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnao1ActionPerformed(evt);
            }
        });

        jnao2.setBackground(new java.awt.Color(255, 0, 0));
        jnao2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jnao2.setText("NAO");
        jnao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnao2ActionPerformed(evt);
            }
        });

        jnao3.setBackground(new java.awt.Color(255, 0, 0));
        jnao3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jnao3.setText("NAO");
        jnao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnao3ActionPerformed(evt);
            }
        });

        jnao4.setBackground(new java.awt.Color(255, 0, 0));
        jnao4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jnao4.setText("NAO");
        jnao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnao4ActionPerformed(evt);
            }
        });

        jnao5.setBackground(new java.awt.Color(255, 0, 0));
        jnao5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jnao5.setText("NAO");
        jnao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnao5ActionPerformed(evt);
            }
        });

        jmen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jmen.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jmen, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonmanu)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jnao2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jsim2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jnao1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jsim1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jnao3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jnao4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jnao5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jsim3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jsim4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jsim5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGap(70, 70, 70))))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jteste, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsim1)
                    .addComponent(jnao1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsim2)
                    .addComponent(jnao2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsim3)
                    .addComponent(jnao3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsim4)
                    .addComponent(jnao4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsim5)
                    .addComponent(jnao5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jteste, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonmanu)
                    .addComponent(jmen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void teste(){

    }
    private void jButtonmanuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonmanuMouseMoved
            jButtonmanu.setBackground(Color.red);

    }//GEN-LAST:event_jButtonmanuMouseMoved

    private void jButtonmanuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonmanuMouseDragged
        //jButtonmanu.setBackground(Color.red);
    }//GEN-LAST:event_jButtonmanuMouseDragged

    private void jButtonmanuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmanuActionPerformed
        manu manu = new manu();
        teste teste = new teste();
        teste.setVisible(false);
        manu.setVisible(true);
    }//GEN-LAST:event_jButtonmanuActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed


    private void jtesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtesteActionPerformed
      
       String r[] = new String[10];
       r[0] = (String.valueOf(jnao1.isBackgroundSet()));
       r[1] =(String.valueOf(jnao2.isBackgroundSet()));
       r[2] =(String.valueOf(jnao3.isBackgroundSet()));
       r[3] =(String.valueOf(jnao4.isBackgroundSet()));
       r[4] =(String.valueOf(jnao5.isBackgroundSet()));
       r[5] =(String.valueOf(jsim1.isBackgroundSet()));
       r[6] =(String.valueOf(jsim2.isBackgroundSet()));
       r[7] =(String.valueOf(jsim3.isBackgroundSet()));
       r[8] =(String.valueOf(jsim4.isBackgroundSet()));
       r[9] =(String.valueOf(jsim5.isBackgroundSet()));
       

       if(r[0].equals("false")){
           
           if(r[1].equals("false")){
               if(r[2].equals("flase")){
                   if(r[3].equals("false")){
                       jmen.setText("Você provavelmente não tem a Cov-19, fique calmo e em casa!");
                   }
                   else if(r[9].equals("true")){
                       jmen.setText("fique tranquilo e ligue para a central de saude evite sair de casa!!");
                   }else{
                       jmen.setText("Voçe deve ligar para a central evite sair de casa!");
                   }
               }
           }
               
        }
    }//GEN-LAST:event_jtesteActionPerformed

    public teste(JToggleButton jnao1, JToggleButton jnao2, JToggleButton jnao3, JToggleButton jnao4, JToggleButton jnao5, JToggleButton jsim1, JToggleButton jsim2, JToggleButton jsim3, JToggleButton jsim4) {
        this.jnao1 = jnao1;
        this.jnao2 = jnao2;
        this.jnao3 = jnao3;
        this.jnao4 = jnao4;
        this.jnao5 = jnao5;
        this.jsim1 = jsim1;
        this.jsim2 = jsim2;
        this.jsim3 = jsim3;
        this.jsim4 = jsim4;
    }

    public JToggleButton getJnao1() {
        return jnao1;
    }

    public void setJnao1(JToggleButton jnao1) {
        this.jnao1 = jnao1;
    }

    public JToggleButton getJnao2() {
        return jnao2;
    }

    public void setJnao2(JToggleButton jnao2) {
        this.jnao2 = jnao2;
    }

    public JToggleButton getJnao3() {
        return jnao3;
    }

    public void setJnao3(JToggleButton jnao3) {
        this.jnao3 = jnao3;
    }

    public JToggleButton getJnao4() {
        return jnao4;
    }

    public void setJnao4(JToggleButton jnao4) {
        this.jnao4 = jnao4;
    }

    public JToggleButton getJnao5() {
        return jnao5;
    }

    public void setJnao5(JToggleButton jnao5) {
        this.jnao5 = jnao5;
    }

    public JToggleButton getJsim1() {
        return jsim1;
    }

    public void setJsim1(JToggleButton jsim1) {
        this.jsim1 = jsim1;
    }

    public JToggleButton getJsim2() {
        return jsim2;
    }

    public void setJsim2(JToggleButton jsim2) {
        this.jsim2 = jsim2;
    }

    public JToggleButton getJsim3() {
        return jsim3;
    }

    public void setJsim3(JToggleButton jsim3) {
        this.jsim3 = jsim3;
    }

    public JToggleButton getJsim4() {
        return jsim4;
    }

    public void setJsim4(JToggleButton jsim4) {
        this.jsim4 = jsim4;
    }

    public JToggleButton getJsim5() {
        return jsim5;
    }

    public void setJsim5(JToggleButton jsim5) {
        this.jsim5 = jsim5;
    }

    private void jsim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsim1ActionPerformed
        jnao1.setEnabled(false);
        int js1 = 1;
    }//GEN-LAST:event_jsim1ActionPerformed

 
    private void jsim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsim2ActionPerformed
        jnao2.setEnabled(false);
        int js2 = 1;
    }//GEN-LAST:event_jsim2ActionPerformed

    private void jsim3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsim3ActionPerformed
        jnao3.setEnabled(false);
        int js3 = 1;
    }//GEN-LAST:event_jsim3ActionPerformed

    private void jsim4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsim4ActionPerformed
        jnao4.setEnabled(false);
        int js4 = 1;
    }//GEN-LAST:event_jsim4ActionPerformed

    private void jsim5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsim5ActionPerformed
        jnao5.setEnabled(false);
        int js5 = 1;
    }//GEN-LAST:event_jsim5ActionPerformed

    private void jnao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnao1ActionPerformed
       jsim1.setEnabled(false);
        int jn1 = 1;
       
    }//GEN-LAST:event_jnao1ActionPerformed

    private void jnao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnao2ActionPerformed
        jsim2.setEnabled(false);
        int jn2 = 1;
    }//GEN-LAST:event_jnao2ActionPerformed

    private void jnao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnao3ActionPerformed
        jsim3.setEnabled(false);
        int jn3 = 1;
    }//GEN-LAST:event_jnao3ActionPerformed

    private void jnao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnao4ActionPerformed
        jsim4.setEnabled(false);
        int jn4 = 1;
    }//GEN-LAST:event_jnao4ActionPerformed

    private void jnao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnao5ActionPerformed
        jsim5.setEnabled(false);
        int jn5 = 1;
    }//GEN-LAST:event_jnao5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonmanu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jmen;
    private javax.swing.JToggleButton jnao1;
    private javax.swing.JToggleButton jnao2;
    private javax.swing.JToggleButton jnao3;
    private javax.swing.JToggleButton jnao4;
    private javax.swing.JToggleButton jnao5;
    private javax.swing.JToggleButton jsim1;
    private javax.swing.JToggleButton jsim2;
    private javax.swing.JToggleButton jsim3;
    private javax.swing.JToggleButton jsim4;
    private javax.swing.JToggleButton jsim5;
    private javax.swing.JButton jteste;
    // End of variables declaration//GEN-END:variables
}
